import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Live Demo for{" "}
          <a className="https://blog.anishde.dev/powerful-code-blocks-with-code-hike-and-mdx">
            my blog post on setting up Code Hike with Next.JS
          </a>
        </h1>

        <p className={styles.description}>
          Go to{" "}
          <Link href="/code-hike" passHref>
            <a>
              <code>/code-hike</code>
            </a>
          </Link>{" "}
          to see the live preview.
        </p>
      </main>
    </div>
  );
}
